version: '3.1'
services:
  postgresql:
    image: postgres:11.6
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sandbox

  postgresql-test:
    image: postgres:11.6
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sandbox

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  mysql:
    image: mysql:5.7
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3317:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sandbox
      TZ: "Asia/Tokyo"

  mysql-test:
    image: mysql:5.7
    command: >
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3318:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sandbox
      TZ: "Asia/Tokyo"
