version: '3.8'
services:
  ldap:
    image: osixia/openldap:1.4.0
    ports:
      - "389:389"
    environment:
      LDAP_ORGANISATION: "My Company"
      LDAP_DOMAIN: "my-company.com"
      LDAP_ADMIN_PASSWORD: "password"

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    ports:
      - "6443:443"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
