version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:8.0.20
        command: >
          mysqld
          --default-authentication-plugin=mysql_native_password
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_unicode_ci
        ports:
          - "3318:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: sandbox
          TZ: "Asia/Tokyo"

    working_directory: ~/scala-study

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
            - key-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "build.sbt" }}
            - key-{{ .Environment.CACHE_VERSION }}-dependencies-

      - run: cd circleci-example; cat /dev/null | sbt test:compile

      - run: cd circleci-example; cat /dev/null | sbt test:flywayMigrate

      - save_cache:
          paths:
            - ~/.m2
          key: key-{{ .Environment.CACHE_VERSION }}-dependencies-{{ checksum "build.sbt" }}

      - run: cd circleci-example; cat /dev/null | sbt test:test
